pygments: true
auto: true
permalink: none
hashtag: '#btvwag'
twitter_search: 'btvwag'
github_login: 'btvwag'
github_repo: 'btvwag.github.com'
github_language: ['Javascript', 'Ruby', 'PHP', 'Python']
email: info@agilionapps.com

#linkedin_members
linkedin_members: [
'adambouchard',
'p3t3r',
'alanpeabody',
'tristanoneil',
'sbehan',
'mikemccarney',
'mitchlieberman',
'justin-smith/0/9a6/b83',
'stevearrants',
'edwardlucas',
'yiyujia',
'jacksonlatka',
'josh-sled/1/b72/7b7',
'jasonseiler',
'hunterperess',
'nowellstrite',
'robsmart',
'everettmckay',
'dennis-h-doire/6/414/173',
'rebeccagrenier',
'erikwheeler',
'michael-howe/7/5a3/415',
'bradleyholt',
'stephen-prytherch/9/a18/906',
'brie-hoblin/20/698/961',
'brettchalupa',
'gregory-grillone/34/a40/182',
'rene-churchill/0/11b/397',
'daveburkevt',
'robertocampus',
'dancoutu',
'kipsteele',
'victorocastro',
'davelindberg',
'glengehrkens',
'scottnelle',
'karencegalis',
'plainspace',
'david-coutu/4/276/236',
'matthew-moreau/4/431/3a5',
'carl-putscher/4/867/26b',
'geoff-halsted/4/928/211',
'roberthaverly',
'stephen-quick/7/391/280',
'jess-lilly/7/794/17b',
'ericfamiglietti',
'ron-herman/8/260/577',
'marlonbranicki',
'jaseroberts',
'michaelrfowler',
'nszumowski',
'oliver-f-beauchemin/12/328/a54',
'williamcharltonjr',
'john-valance/15/83b/991',
'micahmutrux',
'sivanagarasad-siva/21/8b0/424',
'ken-hewitt/27/572/197',
'forestbond'
]
